name: update messages.txt
on:
  schedule:
    - cron: "*/5 * * * *" # executa a cada 5 minutos
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Run script to fetch messages
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: node index.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          if [ -f messages.txt ]; then
            git add messages.txt

            if git diff --staged --quiet; then
              echo "No changes to commit."
            else
              git commit -m "update: messages.txt em $(date -u '+%Y-%m-%d %H:%M:%S') UTC"

              # Configura URL remota com token para autenticação
              git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/matheusaudibert/imersaoia-ranking.git

              git pull --rebase
              git push origin main
            fi
          else
            echo "messages.txt was not created."
            exit 1
          fi
